/*! الصنّارة (دليل الصياد) — © 2026 Maro Shahaly. جميع الحقوق محفوظة. يُمنع النسخ أو إعادة النشر دون إذن كتابي. */
/* عقد الصيد: رسومات مرسومة خصيصًا للتطبيق (مش منقولة)، ولكل عقدة رابط للرسوم المتحركة خطوة بخطوة على animatedknots.com */
const KNOT_BASE = 'https://www.animatedknots.com/';
const KNOT_EYE = (x, y) => '<g fill="none" stroke="#7E8894" stroke-width="5"><ellipse cx="' + x + '" cy="' + y + '" rx="14" ry="10"/></g><path d="M' + (x + 14) + ' ' + y + ' H' + (x + 70) + '" stroke="#7E8894" stroke-width="6" stroke-linecap="round"/>';
const KNOT_HOOK = (x, y) => '<g fill="none" stroke="#7E8894" stroke-width="5" stroke-linecap="round"><ellipse cx="' + x + '" cy="' + y + '" rx="10" ry="8"/><path d="M' + (x + 10) + ' ' + y + ' H' + (x + 120) + ' a24 24 0 0 1 0 48 h-20"/><path d="M' + (x + 100) + ' ' + (y + 48) + ' l10 -10"/></g>';
const FKNOTS = [
  { id: 'clinch', t: 'عقدة الكلينش المحسّنة', en: 'Improved Clinch Knot', u: 'improved-clinch-knot', use: 'ربط السنارة أو الرابلة أو المدوّر في الخيط النايلون. أشهر عقدة للمبتدئين.', steps: ['عدّي الخيط في عين السنارة.', 'لف الطرف حوالين الخيط الأساسي 5–7 لفات.', 'رجّع الطرف من الحلقة الصغيرة اللي جنب العين.', 'عدّيه تاني من الحلقة الكبيرة اللي اتكوّنت.', 'بلّ العقدة بالمياه واشدها بالراحة، واقطع الزيادة.'],
    svg: KNOT_EYE(30, 60) + '<path d="M44 60 C70 40,80 80,100 60 C120 40,130 80,150 60 C170 40,180 80,200 60 H300" fill="none" stroke="var(--teal)" stroke-width="3.5"/><path d="M44 60 C60 75,190 80,205 66" fill="none" stroke="#E8A800" stroke-width="3" stroke-dasharray="6 4"/>' },
  { id: 'palomar', t: 'عقدة البالومار', en: 'Palomar Knot', u: 'palomar-knot', use: 'من أقوى عقد ربط السنارة، وممتازة مع البريد (الخيط المضفّر).', steps: ['اطوي الخيط مرتين (عروة) وعدّي العروة في عين السنارة.', 'اعمل عقدة بسيطة بالعروة حوالين الخيط من غير ما تشدها.', 'عدّي السنارة كلها من جوّه العروة.', 'بلّ واشد الطرفين لحد ما العقدة تقفل فوق العين.'],
    svg: KNOT_EYE(30, 60) + '<path d="M44 54 H120 M44 66 H120" stroke="var(--teal)" stroke-width="3.5"/><path d="M120 54 C150 30,170 90,140 70 C120 60,150 40,170 56 H300 M120 66 C150 80,170 70,180 64" fill="none" stroke="var(--teal)" stroke-width="3.5"/><circle cx="140" cy="60" r="16" fill="none" stroke="#E8A800" stroke-width="2.5" stroke-dasharray="5 4"/>' },
  { id: 'uni', t: 'عقدة اليوني (الجريندر)', en: 'Uni Knot', u: 'uni-knot', use: 'عقدة متعددة الاستخدام: لربط السنارة، أو لربط الخيط في بكرة الماكينة.', steps: ['عدّي الخيط من العين ورجّعه جنب الخيط الأساسي.', 'اعمل بالطرف حلقة فوق الخطين.', 'لف الطرف جوّه الحلقة حوالين الخطين 5–6 لفات.', 'اشد الطرف عشان اللفات تقفل، وبعدين زقّ العقدة لحد العين.'],
    svg: KNOT_EYE(30, 60) + '<path d="M44 56 H300 M44 64 H120" stroke="var(--teal)" stroke-width="3.5"/>' + [0, 1, 2, 3, 4, 5].map(i => '<ellipse cx="' + (130 + i * 14) + '" cy="60" rx="5" ry="14" fill="none" stroke="var(--teal)" stroke-width="3"/>').join('') },
  { id: 'snell', t: 'عقدة السنيل', en: 'Snell Knot', u: 'snell-knot', use: 'ربط السنارة من الساق مباشرة (خصوصًا السنانير الدائرية والطعم الحي): الشد بيبقى في خط مستقيم مع الساق.', steps: ['عدّي الخيط في العين ومدّه على طول الساق.', 'اعمل عروة ولف الطرف حوالين الساق والخيط 7–10 لفات من جهة الانحناء ناحية العين.', 'اشد الخيط الأساسي عشان اللفات تتقفل على الساق.'],
    svg: KNOT_HOOK(30, 40) + [0, 1, 2, 3, 4, 5, 6].map(i => '<ellipse cx="' + (70 + i * 9) + '" cy="40" rx="4" ry="10" fill="none" stroke="var(--teal)" stroke-width="2.6"/>').join('') + '<path d="M20 40 H-10" stroke="var(--teal)" stroke-width="3"/><path d="M30 32 L0 20" stroke="var(--teal)" stroke-width="3"/>' },
  { id: 'doubleuni', t: 'عقدة اليوني المزدوجة', en: 'Double Uni Knot', u: 'double-uni-knot', use: 'وصل خيطين ببعض (البريد بالليدر، أو خيطين نايلون مختلفين في السُمك).', steps: ['حط الخيطين جنب بعض في اتجاهين عكس بعض.', 'اعمل عقدة يوني بطرف الخيط الأول حوالين التاني.', 'اعمل عقدة يوني تانية بطرف الخيط التاني حوالين الأول.', 'اشد الخيطين الأساسيين لحد ما العقدتين يتقابلوا.'],
    svg: '<path d="M10 54 H200 M300 66 H100" stroke="var(--teal)" stroke-width="3.5"/>' + [0, 1, 2, 3, 4].map(i => '<ellipse cx="' + (110 + i * 12) + '" cy="60" rx="5" ry="13" fill="none" stroke="var(--teal)" stroke-width="3"/>').join('') + [0, 1, 2, 3, 4].map(i => '<ellipse cx="' + (178 + i * 12) + '" cy="60" rx="5" ry="13" fill="none" stroke="#E8A800" stroke-width="3"/>').join('') },
  { id: 'fg', t: 'عقدة الـ FG', en: 'FG Knot', u: 'fg-knot', use: 'أقوى وأنحف وصلة بين البريد والليدر (فلوروكاربون أو نايلون)، بتعدّي من حلقات البوصة بسهولة في التشويح.', steps: ['شد البريد كويس، وحط الليدر عليه بزاوية.', 'لف البريد حوالين الليدر بالتبادل (فوق وتحت) حوالي 20 مرة.', 'اقفل بعقد نص-عقدة (half hitch) على الخطين كام مرة.', 'اقطع طرف الليدر واقفل بنص-عقدات على البريد بس.'],
    svg: '<path d="M10 60 H300" stroke="#E8A800" stroke-width="2.5"/><path d="M120 60 L300 60" stroke="var(--teal)" stroke-width="5"/>' + Array.from({ length: 14 }, (_, i) => '<path d="M' + (126 + i * 8) + ' 52 L' + (130 + i * 8) + ' 68" stroke="#E8A800" stroke-width="2"/>').join('') },
  { id: 'albright', t: 'عقدة الألبرايت', en: 'Albright Knot', u: 'albright-knot', use: 'وصل خيطين مختلفين جدًا في السُمك (خيط رفيع بليدر تخين أو سلك).', steps: ['اطوي الليدر التخين على شكل حرف U.', 'عدّي الخيط الرفيع جوّه الـ U.', 'لفه حوالين الضلعين 10–12 لفة ناحية طرف الـ U.', 'رجّعه من نفس الفتحة اللي دخل منها، واشد بالراحة.'],
    svg: '<path d="M300 52 H90 a8 8 0 0 0 0 16 H200" fill="none" stroke="var(--teal)" stroke-width="5"/><path d="M10 60 H210" stroke="#E8A800" stroke-width="2.5"/>' + Array.from({ length: 9 }, (_, i) => '<ellipse cx="' + (110 + i * 9) + '" cy="60" rx="4" ry="12" fill="none" stroke="#E8A800" stroke-width="2.4"/>').join('') },
  { id: 'surgeonloop', t: 'عروة الجرّاح', en: "Surgeon's Loop", u: 'surgeonsloop/', use: 'عمل عروة (حلقة) سريعة في آخر الخيط لوصلة عروة بعروة أو لتعليق الرصاص.', steps: ['اطوي آخر الخيط عشان تعمل عروة.', 'اعمل عقدة بسيطة بالعروة كلها، وعدّيها مرة كمان (عقدة مزدوجة).', 'اشد العروة والخيط في اتجاهين عكس بعض.'],
    svg: '<path d="M10 60 H140" stroke="var(--teal)" stroke-width="3.5"/><circle cx="150" cy="60" r="12" fill="none" stroke="#E8A800" stroke-width="3"/><path d="M162 54 C220 20,300 40,300 60 C300 80,220 100,162 66" fill="none" stroke="var(--teal)" stroke-width="3.5"/>' },
  { id: 'dropper', t: 'عروة الدروبر (لعمل السبحة)', en: 'Dropper Loop', u: 'dropper-loop-knot', use: 'عمل عروة جانبية في نص الخيط عشان تعلّق فيها سنارة فرعية: أساس عمل السبحة.', steps: ['اعمل حلقة في نص الخيط.', 'لف طرفي الحلقة حوالين بعض 5–6 لفات.', 'افتح فتحة في نص اللفات وعدّي منها الحلقة.', 'اشد الطرفين؛ العروة هتطلع عمودية على الخيط.'],
    svg: '<path d="M10 70 H300" stroke="var(--teal)" stroke-width="3.5"/>' + [0, 1, 2, 3].map(i => '<ellipse cx="' + (128 + i * 12) + '" cy="70" rx="5" ry="12" fill="none" stroke="var(--teal)" stroke-width="3"/>').join('') + '<path d="M150 60 C130 10,190 10,170 60" fill="none" stroke="#E8A800" stroke-width="3.5"/>' },
  { id: 'rapala', t: 'عقدة الرابالا (عروة حرّة)', en: 'Rapala Knot', u: 'rapala-knot', use: 'ربط الرابلة بعروة صغيرة حرّة عشان تتحرك وتترقّص بشكل طبيعي.', steps: ['اعمل عقدة بسيطة مفتوحة على بعد 10 سم من الطرف.', 'عدّي الطرف من عين الرابلة ورجّعه من العقدة البسيطة.', 'لفه حوالين الخيط 3–4 لفات، ورجّعه من العقدة، وبعدين من الحلقة الكبيرة.', 'اشد؛ هتفضل عروة صغيرة قدام العين.'],
    svg: '<path d="M30 60 q40 -20 90 -2 q8 4 0 8 q-50 16 -90 -6z" fill="#9FC7D6" stroke="#36667A" stroke-width="2"/><circle cx="26" cy="60" r="5" fill="none" stroke="#7E8894" stroke-width="3"/><ellipse cx="0" cy="60" rx="0" ry="0"/><path d="M21 60 C10 50,10 70,21 64" fill="none" stroke="var(--teal)" stroke-width="3"/><path d="M-20 60 H-60" stroke="var(--teal)" stroke-width="3.5"/>', flip: 1 },
  { id: 'bimini', t: 'عقدة البيميني تويست', en: 'Bimini Twist', u: 'bimini-twist-knot', use: 'عمل دبل لاين (خيط مزدوج) قوي جدًا للصيد التقيل في البحر (تونة، دراك، مارلين).', steps: ['اطوي حوالي متر من الخيط عروة كبيرة.', 'لف العروة 20 لفة (برم).', 'افتح العروة برجليك أو حاجة ثابتة عشان اللفات تتقارب.', 'خلّي الطرف يلف راجع على البرم، واقفل بنص-عقدات.'],
    svg: '<path d="M10 60 H90" stroke="var(--teal)" stroke-width="3.5"/>' + Array.from({ length: 10 }, (_, i) => '<path d="M' + (90 + i * 12) + ' 52 L' + (102 + i * 12) + ' 68 M' + (90 + i * 12) + ' 68 L' + (102 + i * 12) + ' 52" stroke="var(--teal)" stroke-width="2.6"/>').join('') + '<path d="M210 52 C260 30,300 50,300 60 C300 70,260 90,210 68" fill="none" stroke="#E8A800" stroke-width="3"/>' }
];
