/* الأنواع والسلالات داخل صفحة كل نوع: [الاسم العربي, الاسم العلمي, وصف قصير, معرّف نوع في الدليل له صفحة وصورة (اختياري)] */
const VARIANTS = {
  mullet: [['البوري الرمادي (أبو راس)', 'Mugil cephalus', 'الأكبر والأشهر، راسه عريض مفلطح وعينه عليها جفن دهني.', 'mullet'], ['بوري الشفة الغليظة', 'Chelon labrosus', 'شفته العليا تخينة واضحة، في المتوسط.', 'thicklip'], ['الطوبارة (البوري ذهبي الخد)', 'Chelon auratus', 'بقعة دهبية على الغطاء الخيشومي.', 'tobara'], ['الجران (الشفة الرقيقة)', 'Chelon ramada', 'شفته رفيعة، وبيدخل المصبات والبحيرات.'], ['السهلية', 'Oedalechilus labeo', 'شبه البوري: أصغر وشفتها العليا تخينة، جنب الصخور.', 'oedal'], ['بوري البحر الأحمر (أبو شفة)', 'Crenimugil crenilabis', 'بوري الشعاب في البحر الأحمر.']],
  tilapia: [['البلطي النيلي', 'Oreochromis niloticus', 'الأشهر في مصر والمزارع، ديله مخطط بخطوط سودا عرضية.', 'tilapia'], ['البلطي الأزرق (الحساني)', 'Oreochromis aureus', 'لونه أزرق مخضر، بيتحمل البرد أكتر.'], ['البلطي الأخضر', 'Coptodon zillii', 'بيعيش في الترع وسط الحشائش، لونه أخضر زيتوني.'], ['البلطي الجليلي', 'Sarotherodon galilaeus', 'شائع في النيل وبحيرة ناصر.'], ['البلطي الأحمر (هجين مزارع)', 'Oreochromis sp. (هجين)', 'سلالة مزارع لونها أحمر وردي.']],
  gilthead: [['الدنيس (الملكي)', 'Sparus aurata', 'خط دهبي بين العينين وبقعة سودا على الغطاء.', 'gilthead'], ['الشرغوش', 'Diplodus sargus / D. vulgaris', 'دنيس الصخور بخطوط أو بقعة سودا عند الديل.', 'sargo'], ['التيس (الحداد)', 'Diplodus cervinus', '5 خطوط سودا تخينة بعرض الجسم.', 'tees'], ['المرمار', 'Lithognathus mormyrus', 'خطوط عرضية رمادية، بيعيش على الرملة.'], ['المرجان', 'Pagrus pagrus', 'دنيس أحمر قوي على القيعان العميقة.', 'redporgy'], ['الغزيلة', 'Pagellus erythrinus', 'دنيس وردي صغير على الرملة العميقة.'], ['الدنيس الأحمر الياباني', 'Pagrus major', 'نسخة اليابان والصين.', 'redseabream']],
  grouper: [['الهامور المنقط البرتقالي', 'Epinephelus coioides', 'الأشهر في الخليج والبحر الأحمر.', 'grouper'], ['الوقار (هامور المتوسط)', 'Epinephelus marginatus', 'هامور المتوسط البني بنقط فاتحة.', 'grouper_dusky'], ['الناجل', 'Plectropomus pessuliferus', 'هامور الشعاب الأحمر بنقط زرقا.', 'nagil'], ['هامور الجوهرة (الكوراليه)', 'Cephalopholis miniata', 'صغير أحمر بنقط زرقا لامعة.'], ['هامور الريشة', 'Variola louti', 'ديله على شكل هلال بحافة صفرا.']],
  tuna: [], 
  bluefin: [['التونة زرقاء الزعنفة الأطلسية', 'Thunnus thynnus', 'الأكبر (حتى 600 كجم).', 'bluefin'], ['التونة صفراء الزعنفة', 'Thunnus albacares', 'زعانف صفرا طويلة.', 'yellowfin'], ['التونة البيضاء (الألباكور)', 'Thunnus alalunga', 'زعنفة صدرية طويلة جدًا.', 'albacore'], ['التونة الوثّابة (السكيبجاك)', 'Katsuwonus pelamis', 'خطوط طولية على البطن.', 'skipjack'], ['التونة الجنوبية', 'Thunnus maccoyii', 'نصف الكرة الجنوبي.', 'sbt'], ['البلاميطة (التونة الصغيرة)', 'Euthynnus alletteratus', 'بقع سودا تحت الزعنفة الصدرية.', 'littletunny'], ['البلميدة', 'Sarda sarda', 'خطوط مايلة على الضهر.', 'bonito']],
  seabass: [['القاروص الأوروبي', 'Dicentrarchus labrax', 'القاروص الأساسي في المتوسط.', 'seabass'], ['القاروص المرقّط', 'Dicentrarchus punctatus', 'أصغر، وعليه نقط سودا.'], ['القاروص الياباني', 'Lateolabrax japonicus', 'نسخة شرق آسيا.', 'jseabass'], ['القاروص المخطط الأمريكي', 'Morone saxatilis', 'خطوط طولية سودا.', 'stripedbass']],
  sardine: [['السردين الأوروبي', 'Sardina pilchardus', 'سردين المتوسط الأساسي.', 'sardine'], ['السردين ذو الخطوط الذهبية', 'Sardinella gibbosa', 'سردين البحر الأحمر.', 'goldsardine'], ['السردين المدوّر (الشبابة)', 'Sardinella aurita', 'شائع على سواحل مصر المتوسطية.'], ['الشيم (الرنجة المستديرة)', 'Etrumeus golanii', 'جسم مستدير.', 'roundherring'], ['الأنشوجة', 'Engraulis encrasicolus', 'بقها كبير بيوصل ورا العين.', 'anchovy']],
  squid: [['الكاليماري (السبيط الأوروبي)', 'Loligo vulgaris', 'الأشهر في المتوسط.', 'squid'], ['الحبار الطيار', 'Todarodes sagittatus', 'حبار أعماق.'], ['حبار الشعاب الكبير', 'Sepioteuthis lessoniana', 'في البحر الأحمر، زعانفه على طول جسمه.'], ['السبيط (الكوتل فيش)', 'Sepia officinalis', 'جسمه عريض وفيه عضمة داخلية.', 'cuttlefish']],
  octopus: [['الأخطبوط الشائع', 'Octopus vulgaris', 'المتوسط والأطلسي.', 'octopus'], ['أخطبوط الشعاب', 'Octopus cyanea', 'في البحر الأحمر، بينشط بالنهار.']],
  lobster: [['الإستاكوزا الشوكية المتوسطية', 'Palinurus elephas', 'من غير كلبشات، قرونها طويلة شوكية.', 'lobster'], ['إستاكوزا البحر الأحمر الملونة', 'Panulirus versicolor', 'لون أزرق وأخضر وأبيض.'], ['إستاكوزا الكلبشات الأوروبية', 'Homarus gammarus', 'كلبشات كبيرة، مياه أبرد.'], ['إستاكوزا المياه العذبة (جمبري النيل)', 'Procambarus clarkii', 'دخيلة في النيل والترع.', 'crayfish'], ['الشيكال (الجمبري الكدّاب)', 'Squilla mantis', 'قشري شبه الجمبري.', 'mantis']],
  bluecrab: [['الكابوريا الزرقاء', 'Callinectes sapidus', 'أرجل زرقا، بتعوم.', 'bluecrab'], ['الكابوريا المرقّطة (الفرعونية)', 'Portunus segnis', 'دخلت من البحر الأحمر، شائعة في بورسعيد.'], ['كابوريا الصخور', 'Pachygrapsus marmoratus', 'صغيرة على صخور الشط.'], ['كابوريا النيل', 'Potamonautes niloticus', 'مياه عذبة.', 'nilecrab']],
  barracuda: [['الباراكودا الكبيرة', 'Sphyraena barracuda', 'الأكبر (حتى 1.7 م)، بقع سودا على البطن.', 'barracuda'], ['المرنة (باراكودا المتوسط)', 'Sphyraena sphyraena', 'أصغر، شائعة في الإسكندرية.'], ['باراكودا الشيفرون', 'Sphyraena qenie', 'أسراب كبيرة في البحر الأحمر.'], ['الباراكودا صفراء الذيل', 'Sphyraena flavicauda', 'صغيرة، ديلها أصفر.']],
  emperor: [['الشعور (الشعري)', 'Lethrinus nebulosus', 'أشهر شعور في البحر الأحمر والخليج.', 'emperor'], ['شعور الشفة الحمرا', 'Lethrinus lentjan', 'حافة حمرا على الغطاء الخيشومي.'], ['شعور الأنف الطويل', 'Lethrinus olivaceus', 'بوز طويل.']],
  snapper: [['النهاش', 'Lutjanus spp.', 'أسماك شعاب بأنياب.', 'snapper'], ['النهاش ذو البقعة', 'Lutjanus ehrenbergii', 'بقعة سودا على الجنب، في البحر الأحمر.'], ['البهار (النهاش الأحمر الكبير)', 'Lutjanus bohar', 'ممكن يحمل سيجواتيرا.'], ['النهاش المانجروف', 'Lutjanus argentimaculatus', 'المصبات والمانجروف.', 'mangrovejack']],
  carp: [['المبروك العادي', 'Cyprinus carpio', 'أبو شوارب.', 'carp'], ['مبروك الحشائش', 'Ctenopharyngodon idella', 'جسم طويل، بياكل نباتات.', 'grasscarp'], ['المبروك الفضي', 'Hypophthalmichthys molitrix', 'فضي، عينه واطية.'], ['الكوي (مبروك الزينة)', 'Cyprinus rubrofuscus', 'ملون للأحواض.', 'koi']],
  clarias: [['القرموط الأفريقي', 'Clarias gariepinus', 'الأشهر في النيل والمزارع.', 'clarias'], ['البياض الأفريقي', 'Bagrus bajad', 'أملس من غير قشر، لحمه من غير سافي.', 'bagrus'], ['الشال', 'Synodontis schall', 'قرموط صغير بشوكة قوية.']],
  nileperch: [['قشر البياض (فرخ النيل)', 'Lates niloticus', 'أكبر سمكة في النيل وبحيرة ناصر.', 'nileperch'], ['الباراموندي', 'Lates calcarifer', 'قريبه الآسيوي.', 'barramundi']],
  conger: [['ثعبان البحر الأوروبي (الكونجر)', 'Conger conger', 'رمادي، من غير قشر، في الصخور.', 'conger'], ['الموراي المرقّط', 'Gymnothorax javanicus', 'ثعبان الشعاب في البحر الأحمر.', 'moray'], ['موراي المتوسط', 'Muraena helena', 'بني بنقط صفرا.'], ['ثعبان المياه العذبة', 'Anguilla anguilla', 'بيعيش في البحيرات والترع، مهدد.']],
  oyster: [['المحار', 'Ostreidae', 'لاصق على الصخور.', 'oyster'], ['محار اللؤلؤ', 'Pinctada spp.', 'صدفي من جوّه.', 'pearloyster'], ['المحارة العملاقة', 'Tridacna spp.', 'في الشعاب.', 'giantclam'], ['محارة القلم', 'Pinna nobilis', 'أكبر صدفة في المتوسط.', 'pinna']],
  clam: [['المحار الرملي (الودع)', 'Ruditapes decussatus', '', 'clam'], ['أم الخلول', 'Donax trunculus', 'دمياط والإسكندرية.', 'donax'], ['الكوكل', 'Cerastoderma spp.', '', 'cockle'], ['محار الموسى', 'Solen / Ensis spp.', '', 'razor'], ['الإسكالوب', 'Pectinidae', '', 'scallop']],
  seasnail: [['الحلزون البحري (الموركس)', 'Hexaplex trunculus', '', 'seasnail'], ['الويلك', 'Buccinum undatum', '', 'whelk'], ['البطلينوس', 'Patella spp.', '', 'limpet'], ['الودعة', 'Cypraeidae', '', 'cowrie'], ['الكونش', 'Aliger gigas', '', 'conch'], ['أذن البحر', 'Haliotis spp.', '', 'abalone']],
  mako: [['قرش الماكو', 'Isurus oxyrinchus', '', 'mako'], ['القرش الأزرق', 'Prionace glauca', '', 'blueshark'], ['القرش أبو مطرقة', 'Sphyrna lewini', '', 'hammerhead'], ['قرش النمر', 'Galeocerdo cuvier', '', 'tigershark'], ['قرش الشعاب أسود الطرف', 'Carcharhinus melanopterus', '', 'blacktip'], ['كلب البحر', 'Mustelus mustelus', '', 'smoothhound'], ['القرش الحوت', 'Rhincodon typus', '', 'whaleshark']],
  rabbitfish: [['البطاطا (السيجان المخطط)', 'Siganus rivulatus', 'خطوط طولية دهبية.', 'rabbitfish'], ['السيجان الداكن', 'Siganus luridus', 'بني غامق.'], ['السيجان المرقّط', 'Siganus stellatus', 'في البحر الأحمر، ديله أصفر.']],
  lagocephalus: [['الأرنب (السمكة المنتفخة الفضية)', 'Lagocephalus sceleratus', 'سامة جدًا: ممنوع أكلها.', 'lagocephalus'], ['المنتفخة المرقّطة', 'Arothron hispidus', 'في البحر الأحمر، سامة.'], ['المنتفخة النجمية', 'Arothron stellatus', 'كبيرة بنقط سودا، سامة.']],
  dorado: [['الحصان (الدورادو)', 'Coryphaena hippurus', 'جبهة الذكر عالية.', 'dorado'], ['الدورادو القزم', 'Coryphaena equiselis', 'أصغر، المحيط المفتوح.']],
  trout: []
};
VARIANTS.yellowfin = VARIANTS.albacore = VARIANTS.skipjack = VARIANTS.bonito = VARIANTS.littletunny = VARIANTS.sbt = VARIANTS.bluefin;
VARIANTS.thicklip = VARIANTS.tobara = VARIANTS.oedal = VARIANTS.mullet; VARIANTS.grouper_dusky = VARIANTS.nagil = VARIANTS.grouper; VARIANTS.sargo = VARIANTS.tees = VARIANTS.redporgy = VARIANTS.redseabream = VARIANTS.gilthead;
VARIANTS.cuttlefish = VARIANTS.squid; VARIANTS.crayfish = VARIANTS.mantis = VARIANTS.lobster; VARIANTS.nilecrab = VARIANTS.bluecrab; VARIANTS.grasscarp = VARIANTS.koi = VARIANTS.carp;
VARIANTS.bagrus = VARIANTS.clarias; VARIANTS.moray = VARIANTS.conger; VARIANTS.pearloyster = VARIANTS.giantclam = VARIANTS.pinna = VARIANTS.oyster;
VARIANTS.donax = VARIANTS.cockle = VARIANTS.razor = VARIANTS.scallop = VARIANTS.clam; VARIANTS.whelk = VARIANTS.limpet = VARIANTS.cowrie = VARIANTS.conch = VARIANTS.abalone = VARIANTS.seasnail;
VARIANTS.blueshark = VARIANTS.hammerhead = VARIANTS.tigershark = VARIANTS.blacktip = VARIANTS.smoothhound = VARIANTS.whaleshark = VARIANTS.mako; VARIANTS.barramundi = VARIANTS.nileperch;
VARIANTS.rainbow = VARIANTS.brown = VARIANTS.atlsalmon = VARIANTS.arcticchar = [['تراوت قوس قزح', 'Oncorhynchus mykiss', '', 'rainbow'], ['التراوت البني', 'Salmo trutta', '', 'brown'], ['السلمون الأطلسي', 'Salmo salar', '', 'atlsalmon'], ['الشار القطبي', 'Salvelinus alpinus', '', 'arcticchar'], ['سلمون الشينوك', 'Oncorhynchus tshawytscha', '', 'chinook'], ['سلمون الكوهو', 'Oncorhynchus kisutch', '', 'coho']];
VARIANTS.chinook = VARIANTS.coho = VARIANTS.rainbow;
delete VARIANTS.tuna; delete VARIANTS.trout;
VARIANTS.bagrus = VARIANTS.docmak = VARIANTS.labeo = VARIANTS.bynni = [['البياض الأفريقي', 'Bagrus bajad', 'من غير قشر، شوارب طويلة، لحم من غير سافي، مفترس.', 'bagrus'], ['الدقماق', 'Bagrus docmak', 'بياض أكبر وأغمق.', 'docmak'], ['اللبيس', 'Labeo niloticus', 'قشر فضي، بق سفلي بشفايف تخينة، نباتي، فيه سافي.', 'labeo'], ['البني', 'Labeobarbus bynni', 'قشر دهبي/نحاسي، شاربين قصيرين، أكل متنوع، فيه سافي.', 'bynni'], ['القرموط الأفريقي', 'Clarias gariepinus', '', 'clarias'], ['قشر البياض', 'Lates niloticus', '', 'nileperch']];
VARIANTS.orca = VARIANTS.bottlenose = VARIANTS.spinner = VARIANTS.commondolphin = VARIANTS.risso = VARIANTS.pilot = [['الأوركا (الحوت القاتل)', 'Orcinus orca', 'أكبر الدلافين.', 'orca'], ['الحوت الطيار', 'Globicephala melas', '', 'pilot'], ['دلفين ريسو', 'Grampus griseus', '', 'risso'], ['الدلفين قاروري الأنف', 'Tursiops truncatus', '', 'bottlenose'], ['الدلفين الشائع', 'Delphinus delphis', '', 'commondolphin'], ['الدلفين الدوّار', 'Stenella longirostris', '', 'spinner'], ['خنزير البحر', 'Phocoena phocoena', 'فصيلة قريبة (Phocoenidae).', 'porpoise']];
VARIANTS.porpoise = VARIANTS.orca;
VARIANTS.bluewhale = VARIANTS.humpback = VARIANTS.fin = VARIANTS.minke = VARIANTS.brydes = VARIANTS.grey = VARIANTS.right = VARIANTS.bowhead = [['الحوت الأزرق', 'Balaenoptera musculus', 'رورقوال', 'bluewhale'], ['الحوت الزعنفي', 'Balaenoptera physalus', 'رورقوال', 'fin'], ['حوت برايد', 'Balaenoptera edeni', 'رورقوال', 'brydes'], ['حوت المنك', 'Balaenoptera acutorostrata', 'رورقوال', 'minke'], ['الحوت الأحدب', 'Megaptera novaeangliae', 'رورقوال', 'humpback'], ['الحوت الرمادي', 'Eschrichtius robustus', 'فصيلة الحيتان الرمادية', 'grey'], ['الحوت الصائب', 'Eubalaena glacialis', 'فصيلة الحيتان الصائبة', 'right'], ['الحوت مقوّس الرأس', 'Balaena mysticetus', 'فصيلة الحيتان الصائبة', 'bowhead']];
VARIANTS.sperm = VARIANTS.beluga = VARIANTS.narwhal = VARIANTS.beaked = [['حوت العنبر', 'Physeter macrocephalus', 'حيتان مسننة', 'sperm'], ['حوت كوفييه المنقاري', 'Ziphius cavirostris', 'حيتان منقارية', 'beaked'], ['البيلوغا', 'Delphinapterus leucas', 'Monodontidae', 'beluga'], ['الناروال', 'Monodon monoceros', 'Monodontidae', 'narwhal'], ['الأوركا', 'Orcinus orca', 'Delphinidae', 'orca']];
VARIANTS.dugong = VARIANTS.manatee = VARIANTS.monkseal = [['الأطوم', 'Dugong dugon', 'البحر الأحمر', 'dugong'], ['خروف البحر', 'Trichechus manatus', 'الكاريبي وفلوريدا', 'manatee'], ['فقمة الراهب المتوسطية', 'Monachus monachus', 'المتوسط', 'monkseal']];
VARIANTS.greenturtle = VARIANTS.loggerhead = VARIANTS.hawksbill = [['السلحفاة الخضراء', 'Chelonia mydas', '', 'greenturtle'], ['السلحفاة ضخمة الرأس', 'Caretta caretta', '', 'loggerhead'], ['السلحفاة صقرية المنقار', 'Eretmochelys imbricata', '', 'hawksbill']];
VARIANTS.mako = VARIANTS.blueshark = VARIANTS.hammerhead = VARIANTS.tigershark = VARIANTS.blacktip = VARIANTS.smoothhound = VARIANTS.whaleshark = VARIANTS.greatwhite = VARIANTS.bullshark = VARIANTS.oceanicwt = VARIANTS.nurse = VARIANTS.mako.concat([['القرش الأبيض الكبير', 'Carcharodon carcharias', '', 'greatwhite'], ['قرش الثور', 'Carcharhinus leucas', '', 'bullshark'], ['القرش المحيطي أبيض الطرف', 'Carcharhinus longimanus', '', 'oceanicwt'], ['القرش الممرض الأسمر', 'Nebrius ferrugineus', '', 'nurse']]);
VARIANTS.mantaray = VARIANTS.eagleray = VARIANTS.stingray = [['الراي مانتا العملاق', 'Mobula birostris', '', 'mantaray'], ['الراي العقاب المرقّط', 'Aetobatus ocellatus', '', 'eagleray'], ['اللخمة منقطة الزرقاء', 'Taeniura lymma', '', 'stingray']];
